Affected/urls.py
from django.urls import path
from Affected.views import event, relief, ajax


app_name = 'affected'


urlpatterns = [
    path('events/', event.EventListView.as_view(), name='event_list'),
    path('events/<int:pk>/', event.EventDetailView.as_view(),
         name='event_detail'),
    path('events/create/', event.EventCreateView.as_view(),
         name='event_create'),
    path('map/events/create/', event.MapEventCreateView.as_view(),
         name='map_event_create'),
    path('events/update/<int:pk>/', event.EventUpdateView.as_view(),
         name='event_edit'),
    path('events/delete/<int:pk>/', event.EventDeleteView.as_view(),
         name='event_delete'),
    # Relief Request URLs =====================================================
    path('relief-request', relief.ReliefRequestListView.as_view(),
         name='relief_request_list'),
    path('relief-request/<int:pk>/', relief.ReliefRequestDetailView.as_view(),
         name='relief_request_detail'),
    path('relief-request/create/', relief.ReliefRequestCreateView.as_view(),
         name='relief_request_create'),
    path('relief-request/update/<int:pk>/',
         relief.ReliefRequestUpdateView.as_view(),
         name='relief_request_edit'),
    path('relief-request/delete/<int:pk>/',
         relief.ReliefRequestDeleteView.as_view(),
         name='relief_request_delete'),

    # AJAX URL for deleting an event
    path('events/delete/<int:event_id>/', ajax.get_event_delete,
         name='ajax_event_delete'),
    path('relief/request/delete/<int:relief_request_id>/',
         ajax.get_relief_request_delete, name='ajax_relief_request_delete'),
]

Task/urls.py
from django.urls import path
from .views import (
    TaskListView, task_self_assign, task_update, update_checklist,
    update_task_status, TaskDetailView, TaskCommentView, volunteers_request_view,
    VolunteersRequestListView, volunteers_request_approve, volunteers_request_reject,
    VolunteersRequestDetailView
)

app_name = 'task'


urlpatterns = [
    path('task/self-assign/<int:pk>/', task_self_assign, name='task_self_assign'),
    path('task/update/<int:pk>/', task_update, name='task_update'),
    path('<int:task_id>/update_checklist/', update_checklist, name='update_checklist'),
    path('tasks/<int:task_id>/<str:new_status>/update_status/', update_task_status, name='update_task_status'),
    path('tasks/<int:pk>/', TaskListView.as_view(), name='task_list'),
    path('tasks/<int:pk>/details/<int:task_id>/', TaskDetailView.as_view(), name='task_detail'),
    path('comment/<int:pk>/', TaskCommentView.as_view(), name='task_comment'),
    path('volunteers/request/<int:pk>/', volunteers_request_view, name='volunteers_request'),
    path('volunteers/request/list/', VolunteersRequestListView.as_view(), name='volunteers_request_list'),
    path('volunteers/request/<int:pk>/approve/', volunteers_request_approve, name='volunteers_request_approve'),
    path('volunteers/request/<int:pk>/reject/', volunteers_request_reject, name='volunteers_request_reject'),
    path('volunteers/request/details/<int:pk>/', VolunteersRequestDetailView.as_view(), name='volunteers_request_detail'),
]

crisis_relief/urls.py
# crisis_relief/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('affected/', include('Affected.urls')),
    path('task/', include('Task.urls')),
    path('donate/', include('Donors.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Affected/models/event.py
from django.db import models
from django.db.models import JSONField
from .relief import STATUS_CHOICES

EVENT_TYPE_CHOICES = [
    ('flood', 'Flood'),
    ('fire', 'Fire'),
    ('earthquake', 'Earthquake'),
    ('pandemic', 'Pandemic'),
]

INTENSITY_CHOICES = [
    ('low', 'Low'),
    ('medium', 'Medium'),
    ('high', 'High'),
]


class Event(models.Model):
    """Model representing an event that affects people."""
    user = models.ForeignKey(
        'core.User', on_delete=models.CASCADE, related_name='events', null=True
    )
    event_type = models.CharField(
        max_length=20, choices=EVENT_TYPE_CHOICES, default='flood'
    )
    specific_details = JSONField(null=True, blank=True)
    title = models.CharField(max_length=100)
    intensity = models.CharField(
        max_length=20, choices=INTENSITY_CHOICES, default='high'
    )
    color = models.CharField(max_length=7, default='#FF0000')
    description = models.TextField()
    date = models.DateTimeField()
    latitude = models.FloatField()
    longitude = models.FloatField()
    location = models.CharField(max_length=255)
    radius = models.FloatField()
    affected_people = models.IntegerField()
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='open'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.intensity == 'low':
            self.color = '#81e008'
        elif self.intensity == 'medium':
            self.color = '#e0b208'
        elif self.intensity == 'high':
            self.color = '#FF0000'
        super().save(*args, **kwargs)


class AffectedPeopleImages(models.Model):
    """ Affected people images model """
    event_type = models.CharField(
        max_length=20, choices=EVENT_TYPE_CHOICES, default='flood'
    )
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='affected_people_images/')
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Affected/models/relief.py
from django.db import models
from core.models import User


CATEGORY_CHOICES = [
    ('food', 'Food'),
    ('shelter', 'Shelter'),
    ('medical', 'Medical Supplies'),
    ('water', 'Clean Water'),
    ('other', 'Other'),
]


STATUS_CHOICES = [
    ('open', 'Open'),
    ('closed', 'Closed'),
    ('in_progress', 'In Progress'),
]


class ReliefRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(
        'Event', on_delete=models.CASCADE, related_name='relief_requests',
        null=True
    )
    title = models.CharField(max_length=100)
    description = models.TextField()
    category = models.CharField(max_length=20, choices=CATEGORY_CHOICES)
    quantity = models.PositiveIntegerField(default=1)
    location = models.CharField(max_length=100)
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='open'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

Affected/forms.py
from django import forms
from Affected.models import ReliefRequest, Event


class RequestForm(forms.ModelForm):
    class Meta:
        model = ReliefRequest
        fields = [
            'event', 'title', 'category', 'location', 'quantity',
            'description',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'event': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(RequestForm, self).__init__(*args, **kwargs)
        if user:
            address_parts = []
            if user.address:
                address_parts.append(user.address)
            self.fields['location'].initial = ', '.join(filter(None, address_parts))


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['title', 'date', 'intensity', 'latitude', 'longitude',
                  'location', 'radius', 'affected_people', 'status',
                  'description']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'date': forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'datetime-local',
                }
            ),
            'latitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'longitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'location': forms.TextInput(attrs={'class': 'form-control'}),
            'radius': forms.NumberInput(attrs={'class': 'form-control'}),
            'affected_people': forms.NumberInput(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'title': 'Event Title',
            'date': 'Event Date',
            'latitude': 'Latitude',
            'longitude': 'Longitude',
            'location': 'Location',
            'radius': 'Radius (in km)',
            'affected_people': 'Affected People Count',
            'status': 'Status',
            'description': 'Description',
        }

Affected/views/ajax.py
# ajax
from django.http import JsonResponse
from Affected.models import Event, ReliefRequest


def get_event_delete(request, event_id):
    """
    Handle the deletion of an event.
    """
    if request.method == 'POST':
        try:
            event = Event.objects.get(id=event_id)
            event.delete()
            return JsonResponse({'status': 'success'})
        except Event.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Event not found'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method'})


def get_relief_request_delete(request, relief_request_id):
    """
    Handle the deletion of a relief request.
    """
    if request.method == 'POST':
        try:
            relief_request = ReliefRequest.objects.get(id=relief_request_id)
            relief_request.delete()
            return JsonResponse({'status': 'success'})
        except ReliefRequest.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Relief request not found'})
    return JsonResponse({'status': 'error', 'message': 'Invalid request method'})

Affected/views/event.py
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView, View
)
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from Affected.models import Event, ReliefRequest
from Affected.forms import EventForm


class EventListView(LoginRequiredMixin, ListView):
    model = Event
    template_name = 'event/event_list.html'
    context_object_name = 'events'
    login_url = '/login/'

    def get_queryset(self):
        return Event.objects.all()


class EventDetailView(LoginRequiredMixin, DetailView):
    model = Event
    template_name = 'event/event_detail.html'
    context_object_name = 'event'
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['relief_requests'] = ReliefRequest.objects.filter(
            event=self.object
        )
        return context


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm
    template_name = 'event/event_form.html'
    success_url = reverse_lazy('affected:event_list')
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class MapEventCreateView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        print(request.POST.get('date'), "#" * 20)
        event = Event.objects.create(
            user=request.user,
            title=request.POST.get('title'),
            event_type=request.POST.get('event_type'),
            specific_details=request.POST.get('specific_details'),
            intensity=request.POST.get('intensity'),
            description=request.POST.get('description'),
            date=request.POST.get('date'),
            latitude=request.POST.get('latitude'),
            longitude=request.POST.get('longitude'),
            location=request.POST.get('location'),
            radius=request.POST.get('radius'),
            affected_people=request.POST.get('affected_people'),
        )
        return redirect(reverse_lazy('core:albania_map'))


class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'event/event_form.html'
    success_url = reverse_lazy('affected:event_list')
    login_url = '/login/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class EventDeleteView(LoginRequiredMixin, DeleteView):
    model = Event
    template_name = 'event/event_confirm_delete.html'
    success_url = reverse_lazy('affected:event_list')
    login_url = '/login/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['relief_requests'] = ReliefRequest.objects.filter(
            event=self.object
        )
        return context

Affected/views/relief.py
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)
from datetime import datetime
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from Affected.models import ReliefRequest
from Affected.forms import RequestForm
from utils import send_notification_email
from core.models import User


class ReliefRequestListView(LoginRequiredMixin, ListView):
    """
    View to list all relief requests.
    """
    model = ReliefRequest
    template_name = 'affected/relief_request_list.html'
    context_object_name = 'relief_requests'
    paginate_by = 10

    def get_queryset(self):
        return ReliefRequest.objects.all()


class ReliefRequestDetailView(LoginRequiredMixin, DetailView):
    """
    View to display details of a specific relief request.
    """
    model = ReliefRequest
    template_name = 'affected/relief_request_detail.html'
    context_object_name = 'relief_request'


class ReliefRequestCreateView(LoginRequiredMixin, CreateView):
    """
    View to create a new relief request.
    """
    model = ReliefRequest
    form_class = RequestForm
    template_name = 'affected/relief_request_form.html'
    success_url = reverse_lazy('affected:relief_request_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super().form_valid(form)

        recipients = User.objects.filter(
            email__isnull=False,
            user_type__in=['org', 'volunteers']
        ).exclude(email='').values_list('email', flat=True)

        subject = "New Relief Request Submitted"
        heading = "A new relief request has been created"
        message = f"A new relief request was submitted by {self.request.user.get_full_name} on {datetime.now().strftime('%Y-%m-%d %H:%M')}."

        for email in recipients:
            send_notification_email(
                to_email=email,
                heading=heading,
                message=message,
                subject=subject
            )

        return response


class ReliefRequestUpdateView(LoginRequiredMixin, UpdateView):
    """
    View to update an existing relief request.
    """
    model = ReliefRequest
    form_class = RequestForm
    template_name = 'affected/relief_request_form.html'
    success_url = reverse_lazy('affected:relief_request_list')

    def get_queryset(self):
        return ReliefRequest.objects.filter(user=self.request.user)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ReliefRequestDeleteView(LoginRequiredMixin, DeleteView):
    """
    View to delete a relief request.
    """
    model = ReliefRequest
    template_name = 'affected/relief_request_confirm_delete.html'
    success_url = reverse_lazy('affected:relief_request_list')

    def get_queryset(self):
        return ReliefRequest.objects.filter(user=self.request.user)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return super().delete(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['relief_request'] = self.object
        return context

    def get_success_url(self):
        return reverse_lazy('affected:relief_request_list')

templates/affected/relief_request_detail.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-8">
            <h3 class="card-title">Relief Request Detail</h3>
        </div>
        <div class="col-4 text-right">
            
            {% if request.user == relief_request.user and relief_request.status == 'open' %}
                                <a href="{% url 'affected:relief_request_edit' relief_request.id %}" class="btn btn-warning">Edit Request</a>
                                {% elif request.user != relief_request.user and relief_request.status == 'open' %}
                                <a href="{% url 'task:task_self_assign' relief_request.id %}" class="btn btn-secondary">
                                    Self Assigned
                                </a>
                                {% endif %}
        </div>
        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">{{ relief_request.title }}</h3>
                </div>
                <div class="card-body">
                    <p><strong>Event:</strong> {{ relief_request.event.title }}</p>
                    <p><strong>Location:</strong> {{ relief_request.event.location }}</p>
                    <p><strong>Date:</strong> {{ relief_request.event.date }}</p>
                    <p><strong>Radius:</strong> {{ relief_request.event.radius }}</p>
                    <p><strong>Affected People:</strong> {{ relief_request.event.affected_people }}</p>
                    <p><strong>Status:</strong>
                        {% if relief_request.status == 'open' %}
                        <span class="badge badge-success">Open</span>
                        {% elif relief_request.status == 'closed' %}
                        <span class="badge badge-danger">Closed</span>
                        {% elif relief_request.status == 'in_progress' %}
                        <span class="badge badge-warning">In Progress</span>
                        {% else %}
                        <span class="badge badge-secondary">Unknown</span>
                        {% endif %}
                    </p>
                    <p><strong>Description:</strong> {{ relief_request.description|safe }}</p>
                    <p><strong>Relief Type:</strong> {{ relief_request.category }}</p>
                    <p><strong>Quantity:</strong> {{ relief_request.quantity }}</p>
                    <p><strong>Requested By:</strong> {{ relief_request.user }}</p>
                    <p><strong>Contact Number:</strong> {{ relief_request.user.phone_number }}</p>
                    <p><strong>Address:</strong> {{ relief_request.user.address }}</p>
                </div>
                <div class="card-footer">
                    <a href="{% url 'affected:relief_request_list' %}" class="btn btn-secondary">Back to Relief Request List</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/affected/relief_request_form.html
{% extends "base/base.html" %}
{% load static crispy_forms_tags %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-6 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Create New Event</h3>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="row">
                            <div class="col-4 my-2">
                                <button type="submit" class="btn btn-primary btn-block">Create Request</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/affected/relief_request_list.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row mb-4">
        <div class="col-8">
            <h3 class="card-title">Relief Request List</h3>
        </div>
        {% if request.user.user_type == 'affected' %}
        <div class="col-4 text-right">
            <a href="{% url 'affected:relief_request_create' %}" class="btn btn-primary">Create New Relief Request</a>
        </div>
        {% endif %}
        <div class="col-12 mt-2">
            <!-- table and data-table -->
            <div class="table">
                <table id="example" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                        <tr>
                            <th>Request ID</th>
                            <th>Relief Title</th>
                            <th>Event</th>
                            <th>Location</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for relief_request in relief_requests %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ relief_request.title }}</td>
                            <td>{{ relief_request.event.title }}</td>
                            <td>{{ relief_request.location }}</td>
                            <td>{{ relief_request.event.date }}</td>
                            <td>
                                {% if relief_request.status == 'open' %}
                                <span class="badge badge-success">Open</span>
                                {% elif relief_request.status == 'closed' %}
                                <span class="badge badge-danger">Closed</span>
                                {% elif relief_request.status == 'in_progress' %}
                                <span class="badge badge-warning">In Progress</span>
                                {% else %}
                                <span class="badge badge-secondary">Unknown</span>
                                {% endif %}
                            </td>
                            <td>
                                <a href="{% url 'affected:relief_request_detail' relief_request.id %}" class="btn btn-info">View</a>
                                {% if request.user == relief_request.user and relief_request.status == 'open' %}
                                <a href="{% url 'affected:relief_request_edit' relief_request.id %}" class="btn btn-warning">Edit</a>
                                <button class="btn btn-danger" value="{{ relief_request.id }}">Delete</button>
                                {% elif request.user != relief_request.user and relief_request.status == 'open' %}
                                <a href="{% url 'task:task_self_assign' relief_request.id %}" class="btn btn-secondary">
                                    Self Assigned
                                </a>
                                {% endif %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(document).ready(function (){
        $(".btn-danger").click(function (){
            var id = $(this).val();
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        url: "{% url 'affected:ajax_relief_request_delete' 0 %}".replace('0', id),
                        type: 'POST',
                        headers: {
                            "X-CSRFToken": "{{ csrf_token }}"
                        },
                        success: function(response) {
                            // Reload the page or remove the row from the table
                            location.reload();
                        },
                        error: function(xhr, status, error) {
                            console.error("Error deleting event:", error);
                        }
                    });
                }
            })
        });
    })
</script>
{% endblock %}